# Generated by Django 5.2.5 on 2025-11-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
