# Generated by Django 5.2.5 on 2025-11-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_expense_category_alter_expense_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='note',
            new_name='notes',
        ),
    ]
