# Generated by Django 5.2.5 on 2025-11-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_note_expense_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='note',
            new_name='notes',
        ),
    ]
