# Generated by Django 5.2.5 on 2025-11-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
